# Thay bằng thông tin bạn lấy ở Bước 1
sonar.projectKey=demo-fullstack-cicd
sonar.organization=hatuananh0405

# Cấu hình giữ nguyên
sonar.projectName=demo-fullstack-cicd
sonar.projectVersion=1.0
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, **/*.test.js, **/*.spec.js
sonar.sourceEncoding=UTF-8