apiVersion: v1
kind: Namespace
metadata:
  name: lab14-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/anhha/mysql-data" # Thư mục thật lưu trữ DB trên ổ cứng máy Worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: lab14-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: lab14-app
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        kubernetes.io/role: worker # Ép chạy bên máy Worker nơi gắn Volume đĩa cứng thật
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "SuperSecretRoot123"
        - name: MYSQL_DATABASE
          value: "NodeTest"
        - name: MYSQL_USER
          value: "nodeuser"
        - name: MYSQL_PASSWORD
          value: "Admin123@"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: lab14-app
spec:
  ports:
  - port: 3306
  selector:
    app: mysql