apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: lab14-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-api
        image: 172.16.5.201:5000/lab11-backend:development-latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "mysql-service.lab14-app.svc.cluster.local" # Gọi qua DNS nội bộ K8s thay cho IP cứng
        - name: DB_USER
          value: "nodeuser"
        - name: DB_PASSWORD
          value: "Admin123@"
        - name: DB_NAME
          value: "NodeTest"
        - name: PORT
          value: "5000"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: lab14-app
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000