apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
      # ⚠️ THÊM ĐOẠN ANNOTATION NÀY ĐỂ KÍCH HOẠT ĐO LƯỜNG TRACING TỰ ĐỘNG
      annotations:
        
        instrumentation.opentelemetry.io/inject-nodejs: "default/backend-autoinstrumentation"
    spec:
      containers:
      - name: backend
        image: DOCKERHUB_PLACEHOLDER/lab14-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: OTEL_SERVICE_NAME
          value: "backend-app"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: DB_HOST
          value: "mysql-svc"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "userpassword"
        - name: DB_NAME
          value: "my_database"
        - name: PORT
          value: "5000"