apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      # BỔ SUNG KHU VỰC ANNOTATIONS NÀY ĐỂ KÍCH HOẠT TRACING
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      labels:
        app: backend-app
    spec:
      # Giữ nguyên cấu hình vượt rào DiskPressure cho Pod ứng dụng (để an toàn trong máy Lab)
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: backend
        # Giữ nguyên placeholder để script CI/CD tự động convert sang thẻ SHA khi build
        image: DOCKERHUB_PLACEHOLDER/lab14-backend:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: ["node"]
        args: ["src/index.js"]
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "192.168.254.140"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "userpassword"
        - name: DB_NAME
          value: "my_database"
        - name: PORT
          value: "5000"